/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package restaurant.system;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import common.OpenPdf;
import dao.BillDao;
import dao.CategoryDao;
import dao.ProductDao;
import java.io.File;
import java.io.FileOutputStream;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import model.Bill;
import model.Category;
import model.Product;

/**
 *
 * @author jrodk
 */
public class PlaceOrder extends javax.swing.JFrame {
   public int billId=1;
   public int grandTotal=0;
   public int productPrice=0;
   public int productTotal=0;
   public String emailPattern="^[a-zA-Z0-9]+[@]+[a-zA-Z0-9]+[.]+[a-zA-Z0-9]+$";
   public String mobileNumberPattern="^[0-9]*$";
   public String userEmail;
    

    /**
     * Creates new form PlaceOrder
     */
    public PlaceOrder() {
        initComponents();
 
    }
    
    public PlaceOrder(String email ) {
        initComponents();
        txtProName.setEditable(false);
        txtProPrice.setEditable(false);
        txtProTotal.setEditable(false);
        btnProAddToCart.setEnabled(false);
        btnGenerateBillPrint.setEnabled(false);
        JFormattedTextField tf=((JSpinner.DefaultEditor)Spinner1.getEditor()).getTextField();
        tf.setEditable(false);
        userEmail=email;
    }
        
    public void productNameByCategory(String category){
        DefaultTableModel dtm=(DefaultTableModel)table1.getModel();
        dtm.setRowCount(0);
        ArrayList<Product>list=ProductDao.getAllRecordsByCategory(category);
        Iterator<Product> itr=list.iterator();
        while(itr.hasNext()){
            Product productobj=itr.next();
            dtm.addRow(new Object[]{productobj.getName()});
        }
        
    }
    
    
        public void filterProductByName(String name,String category){
        DefaultTableModel dtm=(DefaultTableModel)table1.getModel();
        dtm.setRowCount(0);
        ArrayList<Product>list=ProductDao.filterProductByname(name,category);
        Iterator<Product> itr=list.iterator();
        while(itr.hasNext()){
            Product productobj=itr.next();
            dtm.addRow(new Object[]{productobj.getName()});
        }
      }
    
        public void clearProduct(){
            txtProName.setText("");
            txtProPrice.setText("");
            Spinner1.setValue(1);
            txtProTotal.setText("");
            btnProAddToCart.setEnabled(false);   
        }
        
        public void validateField(){
            String customername=txtCusName.getText();
            String customermobilenumber=txtCusMobileNo.getText();
            String customerEmail=txtCusEmail.getText();
            if(!customername.equals("")&&!customerEmail.equals("")&& customermobilenumber.matches(mobileNumberPattern) && customermobilenumber.length()==10&&customerEmail.matches(emailPattern) && grandTotal>0){
                btnGenerateBillPrint.setEnabled(true);
            }
            else{
                btnGenerateBillPrint.setEnabled(false);
            }
            
                
                
                
                
        }
    
    
    
    
    
    
    
    
    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtbillid = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCusName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtCusMobileNo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtCusEmail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        categorybox = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        txtProName = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtProPrice = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        Spinner1 = new javax.swing.JSpinner();
        jLabel13 = new javax.swing.JLabel();
        txtProTotal = new javax.swing.JTextField();
        btnProClear = new javax.swing.JButton();
        btnProAddToCart = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table2 = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        txtGrandTotal = new javax.swing.JLabel();
        btnGenerateBillPrint = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1366, 768));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/place order.png"))); // NOI18N
        jLabel1.setText("Place Order");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 14, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Bill ID:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 62, -1, -1));

        txtbillid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtbillid.setForeground(new java.awt.Color(255, 255, 255));
        txtbillid.setText("--");
        getContentPane().add(txtbillid, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 62, 37, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Customer Details:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 99, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Name:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 137, -1, -1));

        txtCusName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtCusName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCusNameKeyReleased(evt);
            }
        });
        getContentPane().add(txtCusName, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 172, 252, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Mobile Number:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 227, -1, -1));

        txtCusMobileNo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtCusMobileNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCusMobileNoActionPerformed(evt);
            }
        });
        txtCusMobileNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCusMobileNoKeyReleased(evt);
            }
        });
        getContentPane().add(txtCusMobileNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 262, 252, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Email:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 303, -1, -1));

        txtCusEmail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtCusEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCusEmailKeyReleased(evt);
            }
        });
        getContentPane().add(txtCusEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 338, 252, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Catogery");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 62, -1, -1));

        categorybox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryboxActionPerformed(evt);
            }
        });
        getContentPane().add(categorybox, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 97, 252, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Search");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 137, -1, -1));

        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });
        getContentPane().add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 173, 252, -1));

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name"
            }
        ));
        table1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, 252, 460));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Name");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(719, 62, 43, -1));

        txtProName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProNameActionPerformed(evt);
            }
        });
        getContentPane().add(txtProName, new org.netbeans.lib.awtextra.AbsoluteConstraints(719, 97, 252, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Price");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1033, 62, 43, -1));
        getContentPane().add(txtProPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(1033, 97, 252, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Quantity");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(719, 137, -1, -1));

        Spinner1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Spinner1StateChanged(evt);
            }
        });
        getContentPane().add(Spinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(719, 173, 252, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Total");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1033, 137, 43, -1));
        getContentPane().add(txtProTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(1033, 173, 252, -1));

        btnProClear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnProClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clear.png"))); // NOI18N
        btnProClear.setText("Clear");
        btnProClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnProClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(719, 226, -1, 37));

        btnProAddToCart.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnProAddToCart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add to cart.png"))); // NOI18N
        btnProAddToCart.setText("Add to Cart");
        btnProAddToCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProAddToCartActionPerformed(evt);
            }
        });
        getContentPane().add(btnProAddToCart, new org.netbeans.lib.awtextra.AbsoluteConstraints(1175, 226, -1, 37));

        table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Price", "Quantity", "Total"
            }
        ));
        table2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 290, 590, 340));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Grand Total: Rs.");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 690, -1, -1));

        txtGrandTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtGrandTotal.setForeground(new java.awt.Color(255, 255, 255));
        txtGrandTotal.setText("000");
        getContentPane().add(txtGrandTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 690, -1, -1));

        btnGenerateBillPrint.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnGenerateBillPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/generate bill & print.png"))); // NOI18N
        btnGenerateBillPrint.setText("Generate Bill & Print");
        btnGenerateBillPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateBillPrintActionPerformed(evt);
            }
        });
        getContentPane().add(btnGenerateBillPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 680, -1, 30));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/14666-atmosphere-blue-color_solid-calm-directory-1366x768.jpg"))); // NOI18N
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -50, 1650, 870));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Home(userEmail).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnProAddToCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProAddToCartActionPerformed
        // TODO add your handling code here:
        String name=txtProName.getText();
        String price=txtProPrice.getText();
        String quantity=String.valueOf(Spinner1.getValue());
        DefaultTableModel dtm=(DefaultTableModel)table2.getModel();
        dtm.addRow(new Object[]{name,price,quantity,productTotal});
        grandTotal=grandTotal+productTotal;
        txtGrandTotal.setText(String.valueOf(grandTotal));
        clearProduct();
        validateField();
    }//GEN-LAST:event_btnProAddToCartActionPerformed

    private void categoryboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryboxActionPerformed
        // TODO add your handling code here:
        String category=(String)categorybox.getSelectedItem();
        productNameByCategory(category);
        
        
    }//GEN-LAST:event_categoryboxActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void txtProNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProNameActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        billId=Integer.parseInt(BillDao.getId());
        txtbillid.setText(BillDao.getId());
        ArrayList<Category>list=CategoryDao.getAllRecords();
        Iterator<Category>itr=list.iterator();
        while(itr.hasNext()){
            Category categoryobj=itr.next();
            categorybox.addItem(categoryobj.getName());     
        }
        String category=(String)categorybox.getSelectedItem();
        productNameByCategory(category);
        
        
        
        
        
        
    }//GEN-LAST:event_formComponentShown

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        // TODO add your handling code here:
        String name=txtSearch.getText();
        String category=(String)categorybox.getSelectedItem();
        filterProductByName(name, category);
        
        
    }//GEN-LAST:event_txtSearchKeyReleased

    private void table1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table1MouseClicked
        // TODO add your handling code here:
        int index=table1.getSelectedRow();
        TableModel model=table1.getModel();
        String ProductName=model.getValueAt(index, 0).toString();
        Product product=ProductDao.getProductByname(ProductName);
        txtProName.setText(product.getName());
        txtProPrice.setText(product.getPrice());
        Spinner1.setValue(1);
        txtProTotal.setText(product.getPrice());
        productPrice=Integer.parseInt(product.getPrice());
        productTotal=Integer.parseInt(product.getPrice());
        btnProAddToCart.setEnabled(true);
          
    }//GEN-LAST:event_table1MouseClicked

    private void Spinner1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Spinner1StateChanged
        // TODO add your handling code here:
        int quantity=(Integer)Spinner1.getValue();
        if(quantity<=1){
            Spinner1.setValue(1);
            quantity=1;      
        }
        productTotal=productPrice*quantity;
        txtProTotal.setText(String.valueOf(productTotal));
        
        
        
    }//GEN-LAST:event_Spinner1StateChanged

    private void btnGenerateBillPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateBillPrintActionPerformed
        // TODO add your handling code here:
        String customerName=txtCusName.getText();
        String customerMobileNumber=txtCusMobileNo.getText();
        String customerEmail=txtCusEmail.getText();
        SimpleDateFormat dformat=new SimpleDateFormat("dd-mm-yyyy");
        Date date=new Date();
        String todaydate=dformat.format(date);
        String total=String.valueOf(grandTotal);
        String createdBy=userEmail;
        Bill bill=new Bill();
        bill.setId(billId);
        bill.setName(customerName);
        bill.setMobileNumber(customerMobileNumber);
        bill.setEmail(customerEmail);
        bill.setDate(todaydate);
        bill.setTotal(total);
        bill.setCreatedBy(createdBy);
        BillDao.save(bill);
        
        //create document
        String path="C:\\Users\\jrodk\\OneDrive\\Desktop\\pdfs\\Bill";
        com.itextpdf.text.Document doc=new com.itextpdf.text.Document();
        try{
            PdfWriter.getInstance(doc,new FileOutputStream(new File(path+""+billId+".pdf")));
            
            
            doc.open();
            Paragraph restaurantname=new Paragraph("                                   Restaurant Management System\n");
            doc.add(restaurantname);
            Paragraph startline=new Paragraph("************************************************************************************************");
            doc.add(startline);
            Paragraph paragraph3=new Paragraph("\t Bill ID:"+billId+ "\n Customer Name:"+customerName+" \nTotal Paid "+grandTotal);
            doc.add(startline);
            doc.add(paragraph3);
            doc.add(startline);
            PdfPTable tb1=new PdfPTable(4);
            tb1.addCell("Name");
            tb1.addCell("Price");
            tb1.addCell("Quantity");
            tb1.addCell("Total");
            for (int i=0;i<table2.getRowCount();i++){
                String a=table2.getValueAt(i,0).toString();
                String b=table2.getValueAt(i,1).toString();
                String c=table2.getValueAt(i,2).toString();
                String d=table2.getValueAt(i,3).toString();
                tb1.addCell(a);
                tb1.addCell(b);
                tb1.addCell(c);
                tb1.addCell(d);
                
            
                
            }
            doc.add(tb1);
            doc.add(startline);
            Paragraph thanksmsg=new Paragraph("Thank you please visite again");
            doc.add(thanksmsg);
            
            //open pdf 
            OpenPdf.openById(String.valueOf(billId));
             
        
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
            
        }
        doc.close();
        setVisible(false);
        new PlaceOrder(createdBy).setVisible(true);
        
        
               
       
    }//GEN-LAST:event_btnGenerateBillPrintActionPerformed

    private void btnProClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProClearActionPerformed
        // TODO add your handling code here:
        clearProduct();
        
        
    }//GEN-LAST:event_btnProClearActionPerformed

    private void txtCusNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCusNameKeyReleased
        // TODO add your handling code here:
        validateField();
    }//GEN-LAST:event_txtCusNameKeyReleased

    private void txtCusMobileNoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCusMobileNoKeyReleased
        // TODO add your handling code here:
        validateField();
    }//GEN-LAST:event_txtCusMobileNoKeyReleased

    private void txtCusEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCusEmailKeyReleased
        // TODO add your handling code here:
        validateField();
    }//GEN-LAST:event_txtCusEmailKeyReleased

    private void table2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table2MouseClicked
        // TODO add your handling code here:
        int index=table2.getSelectedRow();
        int a=JOptionPane.showConfirmDialog(null,"Do you want to remove this product"," select",JOptionPane.YES_NO_OPTION);
        if(a==0){
            TableModel model=table2.getModel();
            String total=model.getValueAt(index,3).toString();
            grandTotal=grandTotal-Integer.parseInt(total);
            txtGrandTotal.setText(String.valueOf(grandTotal));
            ((DefaultTableModel)table2.getModel()).removeRow(index);
            
        }
        
        
        
        
        
        
        
    }//GEN-LAST:event_table2MouseClicked

    private void txtCusMobileNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCusMobileNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCusMobileNoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlaceOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlaceOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlaceOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlaceOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlaceOrder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner Spinner1;
    private javax.swing.JButton btnGenerateBillPrint;
    private javax.swing.JButton btnProAddToCart;
    private javax.swing.JButton btnProClear;
    private javax.swing.JComboBox<String> categorybox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable table1;
    private javax.swing.JTable table2;
    private javax.swing.JTextField txtCusEmail;
    private javax.swing.JTextField txtCusMobileNo;
    private javax.swing.JTextField txtCusName;
    private javax.swing.JLabel txtGrandTotal;
    private javax.swing.JTextField txtProName;
    private javax.swing.JTextField txtProPrice;
    private javax.swing.JTextField txtProTotal;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JLabel txtbillid;
    // End of variables declaration//GEN-END:variables
}
